chat/urls.py
from django.urls import path, re_path


from chat.views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

labrintask/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import logout
from photo.views import home

from labrintask import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout, name='logout'),
    path('register/', include('users.urls', namespace='users')),
    path('photo/', include('photo.urls', namespace='photo')),
    path('', home, name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.email
        if username == other_username:
            return None
        qlookup1 = Q(first__email=username) & Q(second__email=other_username)
        qlookup2 = Q(first__email=other_username) & Q(second__email=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(email=other_username)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    # def broadcast(self, msg=None):
    #     if msg is not None:
    #         broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
    #         return True
    #     return False


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
            )
        )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="col-md-8">
    <h3 class="my-4"> Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}
    {% endif %}
   </h3>
    <ul id="chat-item">
        {% for chat in object.chatmessage_set.all %}
            <li>{{ chat.message }} via {{ chat.user }}</li>
        {% endfor %}
    </ul>
    <form id="Login" method="post" >
        <input type="hidden" id="myemail" value="{{ user.email }}">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" class="btn btn-primary">
    </form>
    <p></p>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>
    <script>
        var formDate = $("#Login");
        var loc = window.location;
        var message = $("#id_message");
        var chatHolder = $("#chat-item");
        var me = $("#myemail").val();
        var wsStart = 'ws://';
        if (loc.protocol == 'https:'){
            wsStart = 'wss://'
        }
        var endpoint = wsStart + loc.host + loc.pathname;
        var socket = new ReconnectingWebSocket(endpoint);

        socket.onmessage = function(e){
            console.log("message", e);
            var chatDataMsg = JSON.parse(e.data);
            chatHolder.append("<li>" + chatDataMsg.message + " via " + chatDataMsg.username+ "</li>")
        };
        socket.onopen = function(e){
            console.log("open", e);
            formDate.submit(function (event) {
                event.preventDefault();
                var msgText = message.val();
                // chatHolder.append("<li>" + msgText + " via " + me + "</li>")
                var finalData = {
                    'message': msgText
                };
                socket.send(JSON.stringify(finalData));
                formDate[0].reset()
            });
        };
        socket.onerror = function(e){
            console.log("error", e)
        };
        socket.onclose = function(e){
            console.log("close", e)
        };

    </script>
{% endblock %}

chat/templates/inbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>